sonar.projectKey=massey-159251-assignment1-text-editor
sonar.projectName=159.251 Assignment 1 Text Editor
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
